apiVersion: v1
kind: Service
metadata:
  name: web-service-gin-service
  namespace: web-service-gin
spec:
  type: ClusterIP
  selector:
    app: web-service-gin
  ports:
  - port: 3000
    targetPort: 8080
